# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
    GO_MODULES:
        sh: cat go.work | grep -oEh  '\t+(\./*[^[:space:]]*)' | tr -d '\t'

includes:
    tool:
        optional: true
        taskfile: "./gen/taskfiles/Taskfile.tools.yml"
    script:
        optional: true
        taskfile: "./gen/taskfiles/Taskfile.scripts.yml"

tasks:
    generate-taskfiles:
        run: once
        env:
            {
                OUTPUT_DIR: "./out",
                SCRIPTS_DIR: "./scripts",
                TASKFILE_OUTPUT_DIR: "./gen/taskfiles",
            }
        cmds:
            - ./scripts/setup-tools-for-local.sh --generate-taskfiles --skip-build
        sources:
            - ./tools/**/*
            - ./scripts/**/*
        generates:
            - "./gen/taskfiles/**/*"

    local-setup-tools:
        run: once
        deps: [generate-taskfiles]
        env:
            {
                SCRIPTS_DIR: "./scripts",
                TASKFILE_OUTPUT_DIR: "./gen/taskfiles",
                TOOLS_OUTPUT_DIR: "./out/tools",
            }
        cmds:
            - ./scripts/setup-tools-for-local.sh
        sources:
            - ./tools/**/*
            - ./scripts/setup-tools-for-local.sh
            - ./scripts/build-tool.sh
            - go.work.sum
        generates:
            - ./out/tools/**/*

    download-repo-as-tarball:
        desc: Download a specific repository and store it
        vars:
            REPO: "{{.REPO}}"
            ORG: "{{.ORG}}"
            REF: "{{.REF}}"
            PKG: '{{.REPO | lower | replace "-" ""}}'
            PATH: "gen/git-repo-tarballs"
        cmds:
            - ./scripts/download-repo-tarball.sh --repo {{.REPO}} --org {{.ORG}} --ref {{.REF}} {{if .PKG}}--pkg {{.PKG}}{{end}} --path {{.PATH}}
        status:
            - test -d {{.PATH}}/{{.REPO}}/{{.REPO}}.tar.gz

    download-all-repos-as-tarballs:
        desc: Download all configured repositories
        cmds:
            - task: download-repo-as-tarball
              vars:
                  REPO: nvim-lspconfig
                  ORG: neovim
                  REF: tags/v1.3.0
            - task: download-repo-as-tarball
              vars:
                  REPO: vscode-languageserver-node
                  ORG: microsoft
                  REF: tags/release/jsonrpc/9.0.0-next.6

    generate:
        cmds:
            - mockery
            - find ./gen/mockery -type f -not -mmin -1 -delete
        generates:
            - ./gen/mockery/*.go
        sources:
            - ./**/*.go

    test:
        cmd: go test ./...

    install-executables:
        cmds:
            - go install ./cmd/gotmpls

    package-extension:
        dir: code-extension
        cmds:
            - rm -rf node_modules
            - rm -rf out
            - bun install
            - bun run package
            - mv ./retab-*.vsix ~/Downloads
            - open https://marketplace.visualstudio.com/manage/publishers/walteh

    rebuild-extension:
        deps:
            - install-executables
        dir: code-extension
        cmds:
            - rm -rf node_modules
            - rm -rf out
            - bun install
            - bun run build

    sync-go-files:
        desc: Sync Go files from a GitHub repository
        requires:
            {
                vars:
                    [
                        DEST,
                        STRINGS_TO_REPLACE,
                        FILES_TO_IGNORE,
                        SRC_REPO,
                        SRC_REF,
                        SRC_PATH,
                    ],
            }
        method: timestamp
        generates:
            - "{{.DEST}}/*.copy.*"
            - "{{.DEST}}/.copy-status"
            - "!{{.DEST}}/*.patch.go"
        cmds:
            - |
                go run ./cmd/copy-files --src-repo "{{.SRC_REPO}}" --ref "{{.SRC_REF}}" --src-path "{{.SRC_PATH}}" --dest-path "{{.DEST}}" \
                     --replacements '{{toJson .STRINGS_TO_REPLACE}}' --ignore '{{toJson .FILES_TO_IGNORE}}'

    copy-lsp-generator:
        desc: copy LSP protocol generator files from golang/tools
        generates:
            - "./pkg/lsp/protocol/generator/*.go"
            - "!./pkg/lsp/protocol/generator/*.patch.go"

        cmds:
            - task: sync-go-files
              vars:
                  SRC_REPO: github.com/golang/tools
                  SRC_REF: master
                  SRC_PATH: gopls/internal/protocol/generate
                  DEST: ./pkg/lsp/protocol/generator
                  STRINGS_TO_REPLACE:
                      - "func processinline():func processinline_old()"
                      - golang.org/x/tools/internal/jsonrpc2:github.com/creachadair/jrpc2
                      - reply jsonrpc2.Replier, r jsonrpc2.Request:conn \*jrpc2.Server, r \*jrpc2.Request
                      - func genCase(:func genCase_old(
                      - func genFunc(:func genFunc_old(
                      - UnmarshalJSON(r.Params(), \&params):UnmarshalJSON(r, \&params)
                      - reply(ctx, :reply_fwd(ctx, conn, r,
                      - sendParseError(ctx, reply,:sendParseError(ctx, conn, r,
                      - recoverHandlerPanic(r.Method()):recoverHandlerPanic(r.Method)
                      - tsprotocol.go:tsprotocol.gen.go
                      - tsserver.go:tsserver.gen.go
                      - tsclient.go:tsclient.gen.go
                      - tsjson.go:tsjson.gen.go
                  FILES_TO_IGNORE: []

    generate-lsp-protocol:
        deps: [copy-lsp-generator]
        sources:
            - "./pkg/lsp/protocol/generator/*.go"
        generates:
            - "./pkg/lsp/protocol/*.gen.go"
        cmds:
            - go generate ./pkg/lsp/protocol/generator

    go-mod-tidy:
        env:
            {
                GOPROXY: https://proxy.golang.org,
                GOSUMDB: sum.golang.org,
                GOPRIVATE: github.com/walteh,
            }
        cmds:
            - for: { var: GO_MODULES }
              cmd: |
                  cd {{.ITEM}} && go mod tidy

    go-mod-upgrade:
        run: once
        deps: [local-setup-tools]
        env:
            {
                GOPROXY: https://proxy.golang.org,
                GOSUMDB: sum.golang.org,
                GOPRIVATE: github.com/walteh,
            }
        cmds:
            - ./scripts/run-tool.sh go-mod-upgrade --force

    sync-aliasrc:
        desc: sync aliasrc system
        cmds:
            - ./scripts/sync-aliasrc.sh
