#!/usr/bin/env bash
set -euo pipefail

# if first argument is "test", use gotestsum
if [ "${1:-}" == "test" ]; then
	shift
	exec task tool:gotestsum -- "$@"
fi

# otherwise run go directly with all arguments
exec go "$@"
